### PR TITLE
Fix `deploy_contract_cairo0`

### PR DESCRIPTION
**Pull request by karol-bisztyga**

### CODE REVIEW

**Comment by Arcticae** [comment]
This contains unrelated changes from #57

**Comment by karol-bisztyga** [comment]
Thanks for pointing out, I updated this

**Comment by MaksymilianDemitraszek** [comment]
Would be nice if we tested it in protostar though

**Comment by Arcticae** [comment]
Testing should be covered in https://github.com/software-mansion/protostar/pull/1677

**Pull request merged**
